---
# tasks file for aleksandar_toromanov
 - name: download terraform
   get_url: >
           url: https://releases.hashicorp.com/terraform/(( terraform_version ))/terraform_(( terraform_version ))_linux_amd64.zip
           dest: /home/atoromanov/temporary/terraform_(( terraform_version ))_linux_amd64.zip

 - name: extract terraform then install
   unarchove: 
        src: /home/atoromanov/temporary/terraform_(( terraform_version ))_linux_amd64.zip
        dest: /usr/local/bin
        copy: no

 - name: Check Terraform version
   command: "terraform -v"
   register: teravera

 - debug: var=teravera
